name: dispatch dist files to server repository
on:
  push:
    branches:
      - main
    paths:
      - 'dist/**'
jobs:
  dispatch-dist-files:
    name: dispatch-dist-files
    runs-on: ubuntu-latest
    steps:
      - name: Check token
        run: echo ${{ secrets.REPO_ACCESS_TOKEN }}
      - name: dispatch-dist-files
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: ktmage/5sounds-server
          event-type: update-files
