name: dispatch dist files to server repository
on:
  push:
    branches:
      - main
    paths:
      - 'dist/**'
jobs:
  dispatch-dist-files:
    name: dispatch-dist-files
    runs-on: ubuntu-latest
    steps:
      - name: dispatch-dist-files
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: ${{ variables.SERVER_REPO }}
          event-type: update-files
